name: Deploy Demo Page

on:
  # 手动触发
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'public/**'
      - 'index.html'
      - 'vite.config.ts'
      - 'package.json'
      - '.github/workflows/**'
      - '!**.md'
      - '!.gitignore'
      - '!.editorconfig'
      - '!LICENSE'

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.check_commit.outputs.should_deploy }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check commit message
        id: check_commit
        run: |
          if echo "${{ github.event.head_commit.message }}" | grep -i "\[deploy\]"; then
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          else
            echo "should_deploy=false" >> $GITHUB_OUTPUT
          fi

  build-and-deploy:
    needs: check
    if: needs.check.outputs.should_deploy == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      # 类型检查可选，如果当前有类型错误可以暂时注释掉
      # - name: Type Check
      #   run: npm run type-check

      - name: Build Demo
        run: npm run build:demo

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./demo-dist
          force_orphan: true
