name: Deploy Docs

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup npm registry
        run: |
          npm config set registry https://registry.npmmirror.com/
          npm config set strict-ssl false

      - name: Install dependencies
        run: |
          npm install --no-package-lock --legacy-peer-deps
          cd docs
          npm install --no-package-lock --legacy-peer-deps

      - name: Build Docs
        run: |
          cd docs
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
          destination_dir: docs
          force_orphan: true
