name: Deploy Docs

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'  # 指定使用官方源

      # 添加设置 npm 配置的步骤
      - name: Setup npm config
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config list

      - name: Install Dependencies
        run: |
          npm ci --registry=https://registry.npmjs.org/  # 指定使用官方源
          cd docs
          npm ci --registry=https://registry.npmjs.org/  # 指定使用官方源

      - name: Build Docs
        run: |
          cd docs
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./docs/.vitepress/dist
          destination_dir: docs
          force_orphan: true
