name: Deploy Docs

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup npm
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set strict-peer-dependencies false
          npm config set legacy-peer-deps true

      - name: Install root dependencies
        run: npm install --no-audit --no-fund --legacy-peer-deps

      - name: Install docs dependencies
        working-directory: ./docs
        run: npm install --no-audit --no-fund --legacy-peer-deps

      - name: Build Docs
        run: |
          cd docs
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
          destination_dir: docs
          force_orphan: true
